### ISSUE TITLE
add support for import from 2fas

### ISSUE THREAD

**Issue by Nixobe** [ente-io/auth#242]

**Comment by RetriedAgain** [comment]
I hope the following can help in some sense as reference:

Example: andOTP, which is not actively maintained anymore since roughly a year ago [1](https://github.com/andOTP/andOTP).
The andOTP-3 different forms:
1. Plain-Text 
2. Encrypted
3. OpenPGP

I chose the plain-text option Nr. 1, which actually outputs a JSON-one-liner. 
I worked with ChatGPT to generate myself a python-script to convert the JSON into the plain-text format required by ente-auth.
The following takes the JSON-one-liner and prints it to the console. 

```
import json

# Load the JSON data
data = < Here the andOTP-JSON >

# Iterate over the data and format it
formatted_data = []
for item in data:
    formatted_item = f"otpauth://totp/{item['issuer']}: {item['label']}?secret={item['secret']}"
    formatted_data.append(formatted_item)

# Print the formatted data
for item in formatted_data:
    print(item)
   
```
I copy-pasted the output-code into a new YAML-file, and let that YAML-file be imported through ente-auth. All my codes (20+) were imported properly.

**Comment by mq1** [comment]
I just wrote a python script for 2fas backups (thanks @RetriedAgain)

```python
import json


def convert(filename):
    with open(filename) as input_file:
        data = json.load(input_file)

    # delete output.yml if exists
    open("output.yml", "w").close()

    with open("output.yml", "a") as output_file:
        for item in data['services']:
            text = f"otpauth://totp/{item['otp']['issuer']}:{item['otp']['account']}?secret={item['secret']}\n"
            output_file.write(text)


if __name__ == '__main__':
    # make sure to change this to your filename
    convert("Backup_2023-11-22.2fas")
```
