### ISSUE TITLE
CLA is conflicting with GPL license

### ISSUE THREAD

**Issue by kushagharahi** [ente-io/auth#438]
The current CLA conflicts with the GPL license because the Contributor Agreement will allow Ente to re-license contributions at anytime. 

Ideally the CLA is adjusted to explicitly state that contributions will be licensed under the GPL or a compatible license.

I would love to contribute more, but the current CLA is basically free labor under the guise of open source.

**Comment by mnvr** [comment]
Hi Kusha!

>  basically free labor under the guise of open source.

I feel you're veering a bit too much into cynicism here.

You will be surprised to know about the amount I have spent grappling with the questions of open source licensing. The end result doesn't show it, since at the end we've just have a standard GPL + CLA that all other companies who're trying to attain commercial sustainability while remaining open source as their core ethos have done (e.g. you can go look at Signal, or Bitwarden. They're doing the same as us. Will you open an issue in the Signal bugtracker accusing them of seeking "free labour under the guise of open source"?)

After all that long grappling, and listing out and investigating all the variants other companies like us are doing (if we ever catch up over beer I can list out 5 different common variants of approaches that respectable names have taken), we figured KISS was the best approach, and went with the current combination.

We're not open source to "get free labour". We're open source because that's what we believe in, that's the dream we grew up with. If you actually look at the contributions, you'll find that if taken just in terms of just code contributions, keeping our stuff open source is a net-negative for us, since firstly there just isn't that much code that we get, and secondly, it takes a lot of our developer effort to integrate drive by contributions into the rest of the code.

But that's fine, overall it is a net positive - For example, the feedback we get from customers opening issues on our GitHub, telling us what they want, is a great help for us in determining our priority log. So all's good - I just want to tell you that if you believe that we are open source to get "free labour", you're just mistaken.

It's even more ironical here, because auth specifically is _free_, it is our labour of love - it is a problem we solved for ourselves and said to each other: hey this is pretty cool why don't we also open source this, it might help others.

---

I understand where you're coming from. I (personally) hope there are better legal frameworks in the future for how to do the sort of thing we're doing. Right now, we won't be changing what we have - we have spent a lot of time and effort in thinking about this, and have tried to choose something that works best for everyone.

**Comment by kushagharahi** [comment]
I certainly appreciate and see the value on what you all are doing. I would not have contributed or been on this repo otherwise. Definitely understand the amount of work it takes to maintain an opensource repo and can sympathize that it is truly a net negative. 

I apologize for my harsh use of "free labour" and would like to further clarify what I meant. I certainly don't mean that Ente is promoting open source in order to get contributions. My main sticking point is that any contribution made here does not have to remain open source. 

> e.g. you can go look at Signal, or Bitwarden. They're doing the same as us.

Signal has one main big difference in their CLA from the CLA presented here
> provided that in all cases, Signal Messenger will make Your Contributions available under an OSI-approved open source license.
I think what Signal has is a perfectly acceptable compromise here. 

Ultimately, I am asking that you all consider verbiage that protects open source contributions, keeping them open source.

**Comment by mnvr** [comment]
Understood, and thanks for the clarification. Reading my response again, I think I myself might've been too rant-y myself, my apologies!

About that specific line, the other example I mentioned, Bitwarden, doesn't have that. It makes more sense not to include that dependency on OSI (a third party). But at the same time, I can sort of see the spirit of what you're saying too. 

That said, Licenses / CLAs etc are a pandora's box I would rather not reopen at this point - even for changing one line I'll need to reach out for legal counsel etc. How about - I acknowledge the point you're raising, and maybe that wording is something that we can tweak in the future, but I wouldn't want to commit to doing anything for now, it is just too much of a chore 😬

**Comment by mnvr** [comment]
The CLA is what it is, and I’ll close this issue.
